version: '3.6'

services:
  control:
    build: ./control
    stdin_open: true
    tty: true

    volumes:
      - type: bind
        source: ./ansible
        target: /var/ansible

  lb01:
    build: ./base
  app01:
    build: ./base
  app02:
    build: ./base
  db01:
    build: ./base
